apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP # Private IP inside the cluster
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
