# kubectl exec -it postgres -- /bin/bash
# psql postgres -d mydb
# \l -> List databases
# "CREATE TABLE IF NOT EXISTS personas (id SERIAL PRIMARY KEY, nombre VARCHAR(100), email VARCHAR(100));"
# \dt -> List tables
# \q -> Quit psql
# exit -> Exit bash

apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:14
      env:
        - name: POSTGRES_PASSWORD
          value: mysecretpw
        - name: POSTGRES_DB
          value: mydb
      ports:
        - containerPort: 5432
