apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  rootpassword: cm9vdHBhc3N3b3Jk # base64 encoded 'rootpassword'
  username: YWRtaW4= # base64 encoded 'admin'
  password: MTIzNDU= # base64 encoded '12345'
