apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default # very important to set the namespace
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
