# This limits are applied at the container | pod level

apiVersion: v1
kind: LimitRange
metadata:
  name: webapp
  namespace: demo-namespace # Ensure this matches the namespace created in namespace.yml
spec:
  limits:
    - type: Container # Apply limits to each container in the pod | could also be Pod to apply to the whole pod
      max:
        cpu: "2"
        memory: "256Mi"
      min:
        cpu: "100m"
        memory: "64Mi"
      default:
        cpu: "500m"
        memory: "128Mi"
      defaultRequest:
        cpu: "200m"
        memory: "64Mi"
