# in ubuntu, hostname -> hostname -i
# kubectl logs <pod-name>-<pod-id>

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
    - name: http
      port: 8161 # exposed to a browser to see admin console
      nodePort: 30010
    - name: endpoint
      port: 61616 # exposed to other microservices to connect to the queue
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      nodePort: 30020
  type: NodePort
