apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: NodePort # Exposed outside the cluster
  selector:
    app: pgadmin
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31337
